on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: mkdir
        run: |
          mkdir tmp
      - name: cd
        run: |
          cd tmp
          echo "wd is $PWD"
      - name: and-now
        run: |
          echo "Now wd is $PWD"
