on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: set-msys2-dir
        shell: pwsh
        run: |
          echo 'msys2_dir="c:\msys64"' >> $env:GITHUB_ENV
      - name: show-msys2-dir
        run: |
          echo "env:msys2_dir is ${env:msys2_dir}"
          echo "env:msys2_dir no brackets is $env:msys2_dir"
          echo "env.msys2_dir is ${{env.msys2_dir}}"
          echo "env.msys2_dir with spaces is ${{ env.msys2_dir }}"
          echo "msys2_dir is ${msys2_dir}"
